### ISSUE TITLE
Any Updates on Code Release?

### ISSUE THREAD

**Issue by TMats** [maximilianigl/rl-msol#1] opened 2021-01-25 23:44 UTC
Hi, I'm a big fan of your work MSOL from UAI talk! And I'd like to test your idea with our environments. Are there any updates on the code release?
Thank you.

**Comment by maximilianigl** [comment] 2021-01-26 08:08
Ah, sorry, I completely forgot. I'll upload something on the weekend, though I can't promise it will be super cleaned up (yet).

**Comment by TMats** [comment] 2021-01-26 08:16
@maximilianigl Thank you very much!

**Comment by maximilianigl** [comment] 2021-01-30 15:36
Hey, I've uploaded a first version. Unfortunately, it seems there have been some breaking changes to e.g. the gym library, so currently, the code doesn't run as is and I'll need more time to fix it (for our experiments I was using an old Docker container, so I didn't notice those breaking changes). Nevertheless, I wanted to upload something this weekend as that's pretty overdue. I'll ping you on this thread when I got it to run.

**Comment by TMats** [comment] 2021-02-01 08:57
@maximilianigl Thank you very much for uploading and kind reply!

**Comment by abdulhaim** [comment] 2021-02-27 13:01
Hello! Is there any update on this repo? Specifically, I'm interested in exactly which version of Taxi was used to generate experiments. Thank you!

**Comment by maximilianigl** [comment] 2021-02-27 17:28
I've pushed some fixes. It runs now, hopefully I didn't break anything and it is still reproducing the results (didn't double check yet). 
Regarding experiments: The taxi env used is the version `v1` for MSOL, `v2` for Distral(+action). `MyTaxi` is the 'normal' taxi whereas `MyTaxi2A` is the directional version. Terrible naming, I forgot why I called it that.

Let me know if you run into trouble when executing.

**Comment by abdulhaim** [comment] 2021-02-27 18:42
Thanks! I'm still getting this error when trying to run distral (same for MSLOL): 

`ERROR - distral - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "main.py", line 308, in main
    envs = MTSubprocVecEnv(envs)
TypeError: Can't instantiate abstract class MTSubprocVecEnv with abstract methods close`

Perhaps this is a version issue? Could I see your requirements.txt just in case?

**Comment by maximilianigl** [comment] 2021-02-28 11:26
I've started from a new python version and got it to run (commands added to Readme). I've also included the output of `pip freeze`. 

I haven't been able to reproduce your error - my best guess would be that you have a different openai baselines? (Are you maybe using the tf2 one?).

**Comment by maximilianigl** [comment] 2021-02-28 13:48
(Please let me know if you still can't get to run and if you do, what was wrong so I know for next time :) ). 
Also, thanks for trying and helping me debug!

**Comment by abdulhaim** [comment] 2021-03-03 19:13
thanks, it works now :) Another clarification, if you don't mind - what was the reason you decided to one-hot encode the observation space as opposed to using the Taxi Env as is with state-space --> (taxi_row, taxi_col, passenger_location, destination) and changing the destination and passenger location to represent different tasks respectively?

**Comment by maximilianigl** [comment] 2021-03-03 20:40
No reason in particular. I didn't try out the one you suggested but tried a visual encoding. Not sure why I used the one-hot one in the end. The reason I didn't try (taxi_row, taxi_col) is a) I didn't think of it :), and b) gut feeling wise I'd say that one-hot or visual encodings are easier for NNs than numerical values, though I might be wrong.  Also, note that passenger location and destination are not part of the state space here: That's the task information, and if we were to include that into the state-space, then all options would just learn to solve all tasks, because they know which task they're in. In other words, for meaningful options to emerge, we always need information asymmetry between the lower-level policy (which doesn't know the task) and the higher-level policy (which does). In our case, we have a separate higher-level policy per task, but that's kinda the same thing.

**Comment by maximilianigl** [comment] 2021-03-04 07:14
Closing this issue, but let me know if there are any problems.

**Closed as completed by maximilianigl** 2021-03-04 07:14 UTC
